language: node_js
node_js:
  - "0.10"
before_script:
  - cd ./NBlast.Client
  - npm install -g gulp
  - npm install -g coffee-script
  - npm install
script:  npm test

language: csharp
mono:
  - latest
script:
   build.sh

